# Day 04 — Tensors: PyTorch's Building Block

> **Goal:** Learn to create, manipulate, and understand tensors — the data structure behind all of deep learning.

A **tensor** is just a multi-dimensional array (like NumPy's `ndarray`, but with GPU support and automatic differentiation).

| Dimension | Name | Example |
|-----------|------|---------|
| 0D | Scalar | A single loss value: `0.5` |
| 1D | Vector | A bias vector: `[0.1, -0.3, 0.2]` |
| 2D | Matrix | A weight matrix, a grayscale image |
| 3D | 3D Tensor | An RGB image (C, H, W) |
| 4D | 4D Tensor | A batch of images (B, C, H, W) |

In [1]:
import torch
import numpy as np

print(f"PyTorch version: {torch.__version__}")

PyTorch version: 2.12.0


## 1. Creating Tensors

In [2]:
# From a Python list
a = torch.tensor([1, 2, 3, 4])
print("Tensor:", a)
print("Shape:", a.shape)    # torch.Size([4])
print("Dtype:", a.dtype)    # torch.int64

# 2D tensor (matrix)
b = torch.tensor([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0]])
print("\n2D Tensor:\n", b)
print("Shape:", b.shape)    # torch.Size([2, 3])

Tensor: tensor([1, 2, 3, 4])
Shape: torch.Size([4])
Dtype: torch.int64

2D Tensor:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape: torch.Size([2, 3])


### Common Tensor Creation Functions

Besides creating tensors from lists, PyTorch provides many convenience functions similar to NumPy. These are used constantly in deep learning — for initializing weights, creating masks, generating test data, etc.

In [3]:
# Common creation functions
print("zeros(3, 4):\n", torch.zeros(3, 4))
print("\nones(2, 3):\n", torch.ones(2, 3))
print("\nrandn(2, 3) (normal distribution):\n", torch.randn(2, 3))
print("\nrand(2, 3) (uniform [0,1)):\n", torch.rand(2, 3))
print("\narange(0, 10, 2):", torch.arange(0, 10, 2))
print("\nlinspace(0, 1, 5):", torch.linspace(0, 1, 5))
print("\neye(3):\n", torch.eye(3))

zeros(3, 4):
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

ones(2, 3):
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

randn(2, 3) (normal distribution):
 tensor([[ 0.6506,  1.2902,  0.7171],
        [-0.7190,  0.0028,  0.0399]])

rand(2, 3) (uniform [0,1)):
 tensor([[0.7664, 0.9535, 0.4969],
        [0.8048, 0.6359, 0.5256]])

arange(0, 10, 2): tensor([0, 2, 4, 6, 8])

linspace(0, 1, 5): tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

eye(3):
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## 2. Data Types (dtypes)

In DL, you'll mostly use `float32` (the default for weights and data).

In [4]:
# Integer tensor
a = torch.tensor([1, 2, 3])
print(f"a dtype: {a.dtype}")  # int64

# Float tensor (what you'll use for DL)
b = torch.tensor([1.0, 2.0, 3.0])
print(f"b dtype: {b.dtype}")  # float32

# Convert dtype
c = a.float()  # int64 → float32
print(f"c dtype: {c.dtype}")

# Specify dtype at creation
d = torch.zeros(3, dtype=torch.float64)
print(f"d dtype: {d.dtype}")

a dtype: torch.int64
b dtype: torch.float32
c dtype: torch.float32
d dtype: torch.float64


## 3. Shapes, Reshaping & Views

**Shape** is the most important property of a tensor. Get comfortable checking it constantly.

In [5]:
x = torch.arange(12)  # [0, 1, 2, ..., 11]
print("Original:", x, "| shape:", x.shape)

# reshape — change shape, same data
a = x.reshape(3, 4)
print("\nreshape(3, 4):\n", a)

# view — same as reshape (must be contiguous in memory)
b = x.view(4, 3)
print("\nview(4, 3):\n", b)

# -1 means "figure it out"
c = x.reshape(2, -1)  # → (2, 6)
print("\nreshape(2, -1):\n", c, "| shape:", c.shape)

Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]) | shape: torch.Size([12])

reshape(3, 4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

view(4, 3):
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

reshape(2, -1):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]) | shape: torch.Size([2, 6])


### Squeeze, Unsqueeze, and Flatten

These operations are **essential in deep learning** — you'll use them every day:
- `unsqueeze` adds a dimension (e.g., adding a batch dimension before passing to a model)
- `squeeze` removes dimensions of size 1 (e.g., removing batch dim for display)
- `flatten` collapses a multi-dimensional tensor into 1D (e.g., before a fully connected layer)

In [6]:
# Adding/removing dimensions — CRITICAL for DL
x = torch.tensor([1.0, 2.0, 3.0])  # shape: (3,)
print("Original shape:", x.shape)

# unsqueeze — add a dimension
row = x.unsqueeze(0)  # shape: (1, 3) — row vector
col = x.unsqueeze(1)  # shape: (3, 1) — column vector
print("unsqueeze(0):", row.shape)  # (1, 3)
print("unsqueeze(1):", col.shape)  # (3, 1)

# squeeze — remove dimensions of size 1
y = torch.zeros(1, 3, 1)
print("\nBefore squeeze:", y.shape)  # (1, 3, 1)
print("After squeeze:", y.squeeze().shape)  # (3,)

# flatten — collapse to 1D
matrix = torch.randn(3, 4)
print("\nBefore flatten:", matrix.shape)  # (3, 4)
print("After flatten:", matrix.flatten().shape)  # (12,)

Original shape: torch.Size([3])
unsqueeze(0): torch.Size([1, 3])
unsqueeze(1): torch.Size([3, 1])

Before squeeze: torch.Size([1, 3, 1])
After squeeze: torch.Size([3])

Before flatten: torch.Size([3, 4])
After flatten: torch.Size([12])


## 4. Indexing & Slicing

Identical to NumPy!

In [7]:
m = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

print("Element [1, 2]:", m[1, 2])       # 60
print("Row 0:", m[0])                    # [10, 20, 30]
print("Column 1:", m[:, 1])              # [20, 50, 80]
print("Submatrix:\n", m[0:2, 1:3])       # Top-right 2×2
print("Elements > 50:", m[m > 50])       # Boolean indexing

Element [1, 2]: tensor(60)
Row 0: tensor([10, 20, 30])
Column 1: tensor([20, 50, 80])
Submatrix:
 tensor([[20, 30],
        [50, 60]])
Elements > 50: tensor([60, 70, 80, 90])


## 5. Tensor Operations (Math)

In [8]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# Element-wise operations
print("a + b =", a + b)
print("a * b =", a * b)      # Element-wise multiply
print("a ** 2 =", a ** 2)    # Square
print("torch.sqrt(a) =", torch.sqrt(a))
print("torch.exp(a) =", torch.exp(a))

# Reductions
print("\nsum:", a.sum())
print("mean:", a.mean())
print("max:", a.max())
print("argmax:", a.argmax())  # Index of max value
print("argmin:", a.argmin())  # Index of min value


a + b = tensor([5., 7., 9.])
a * b = tensor([ 4., 10., 18.])
a ** 2 = tensor([1., 4., 9.])
torch.sqrt(a) = tensor([1.0000, 1.4142, 1.7321])
torch.exp(a) = tensor([ 2.7183,  7.3891, 20.0855])

sum: tensor(6.)
mean: tensor(2.)
max: tensor(3.)
argmax: tensor(2)
argmin: tensor(0)


In [9]:
# Matrix multiplication — the heart of neural networks!
W = torch.randn(3, 4)  # Weight matrix (3 inputs → 4 outputs)
x = torch.randn(3)     # Input vector

# Three ways to do matrix-vector multiply:
result1 = W.T @ x        # @ operator (transpose W first)
result2 = torch.mv(W.T, x)  # explicit matrix-vector multiply
result3 = x @ W          # vector @ matrix (broadcasts)

print("W shape:", W.shape)
print("x shape:", x.shape)
print("Result shape:", result1.shape)  # (4,)
print("Results match:", torch.allclose(result1, result2))

W shape: torch.Size([3, 4])
x shape: torch.Size([3])
Result shape: torch.Size([4])
Results match: True


## 6. NumPy ↔ PyTorch Conversion

In [10]:
# NumPy → PyTorch
np_array = np.array([1.0, 2.0, 3.0])
tensor = torch.from_numpy(np_array)
print("NumPy → Tensor:", tensor)

# PyTorch → NumPy
tensor = torch.tensor([4.0, 5.0, 6.0])
np_array = tensor.numpy()
print("Tensor → NumPy:", np_array)

# ⚠️ They share memory! Changing one changes the other.
a = np.array([1.0, 2.0, 3.0])
b = torch.from_numpy(a)
a[0] = 999
print("\nShared memory demo:")
print("NumPy array:", a)
print("Torch tensor:", b)  # Also changed!

NumPy → Tensor: tensor([1., 2., 3.], dtype=torch.float64)
Tensor → NumPy: [4. 5. 6.]

Shared memory demo:
NumPy array: [999.   2.   3.]
Torch tensor: tensor([999.,   2.,   3.], dtype=torch.float64)


## 7. CPU vs GPU

In [10]:
# Check if GPU is available
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"MPS available (Apple Silicon): {torch.backends.mps.is_available()}")

# Set device
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(f"Using device: {device}")

# Move tensor to device
x = torch.randn(3, 4)
x_gpu = x.to(device)
print(f"\nTensor device: {x_gpu.device}")

# Move back to CPU (needed for numpy/plotting)
x_cpu = x_gpu.cpu()
print(f"Back to CPU: {x_cpu.device}")

CUDA available: False
MPS available (Apple Silicon): True
Using device: mps

Tensor device: mps:0
Back to CPU: cpu


---
## ✏️ Exercises

In [ ]:
# Exercise 1: Create a tensor of shape (2, 3, 4) filled with random numbers.
# Print its shape, dtype, and total number of elements (.numel()).

# Your code here:

In [ ]:
# Exercise 2: Create a 1D tensor [0, 1, 2, ..., 23] and reshape it to (2, 3, 4).
# Then extract the element at position [1, 2, 3].

# Your code here:

In [ ]:
# Exercise 3: Create two random matrices A (3, 4) and B (4, 5).
# Multiply them using @ and verify the output shape is (3, 5).

# Your code here:

---
## 📝 Key Takeaways

1. **Tensors** = multi-dimensional arrays with GPU support + autograd.
2. **Shape** is everything — check it with `.shape` constantly.
3. **`reshape`/`view`** change shape without copying data.
4. **`unsqueeze`/`squeeze`** add/remove dimensions.
5. **`@`** is matrix multiplication — the core of neural networks.
6. **`.to(device)`** moves tensors between CPU and GPU.
7. **`torch.from_numpy()`** and **`.numpy()`** convert between NumPy and PyTorch.

**Tomorrow:** Autograd — how PyTorch automatically computes gradients!